### ISSUE TITLE
Wrong audio language when playing content

### ISSUE THREAD

**Issue by Ferenc-** [Rafostar/clapper-enhancers#1]
I am not sure where to report this yet, so my apologies in advance if this is not the right place.

When playing content with clapper via the gtuber plugin, there only seems to be one audio track available in clapper,
which is surprising, because gtuber is clearly aware of the multiple tracks.

And unfortunately it is often in a completely wrong language, that does not correspond to locales, nor any settings,
and the user does not understand...
So I guess it is just the first language which got extracted by gtuber.

Unforutnatley this issue makes the gtuber plugin rendered unusable if the content has audio tracks in multiple languages.

**Comment by Rafostar** [comment]
Could you provide video example URI to reproduce/testing?

**Comment by Ferenc-** [comment]
For example: `flatpak run com.github.rafostar.Clapper 'https://www.youtube.com/watch?v=Dtocpvv88gQ'`

**Comment by Rafostar** [comment]
For now I will note the problems with this I have seen so far:
~~1. Itags are the same, so we do not distinguish them (maybe we should use float/double for such cases and add something as point value?)~~ - yt-dlp has this as added `-INDEX` suffix
2. We need to ensure all of them are placed in DASH as separate streams and not different qualities
3. We might want to (optional) introduce stream title to display their languages in UI

**Comment by Rafostar** [comment]
There is now ongoing work with replacing `gtuber` with a new plugin system for Clapper. Since this was opened as an issue with Clapper I will be moving this to the new repo in advance.

**Comment by Rafostar** [comment]
Finally had some time to finish fixing this :smile:
